project:
  type: website

website:
  title: "Personal Site"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/RAbraham
      - icon: twitter
        href: https://twitter.com/TheCodePlumber
format:
  html:
    theme: cosmo
    css: styles.css



